### ISSUE TITLE
Add support for live information grabbing.

### ISSUE THREAD

**Issue by ech0devv** [AndraxDev/speak-gpt#117]
I'd like to be able to ask GPT4o for the weather and get a response, rather than being thrown into a google search. This can also potentially be used for setting timers, checking time, sending texts, making calls etc.

**Comment by ech0devv** [comment]
What I meant is you can give GPT4o access to the internet by telling it to say a certain codeword that triggers a weather response.

**Comment by ech0devv** [comment]
It works pretty well and would make the app more usable as a google assistant replacement

**Comment by AndraxDev** [comment]
I know how to give GPT internet access. This feature is called "function calling". This feature works in the next way: When enabled, your prompt will be extended with JSON object contains function names, params and description. GPT will decide which function to use and will return response extended with JSON object that contains function names along with their params amd parsed values. Then that functions will be called inside app.

But this feature is unstable because it invokes crashes and errors during generation. I need to fix it first before extending function calling capabilities. Launching Google Search has been added as a test that proves Function Calling is working normally. If you read README you will see that it's planned to add device routines so I think your issue in unnecessary for now. Thanks again!
