### ISSUE TITLE
Prompts store

### ISSUE THREAD

**Issue by leyin863** [AndraxDev/speak-gpt#15]
Prompts store network error

**Comment by AndraxDev** [comment]
If you compilied this app from sources you will get network error because my servers are protected by API. If you want to use Prompt Store in your build I can provide server key. Otherwise you can just download app from Releases page or from Google Play. Also your internet provider or router settings may apply additional restrictions. If you persist seeing this error send me your device info: Android version, ROM, app version, device model.

Thanks.

Screenshoot pf test:
![Screenshot_20230427-102413_SpeakGPT.png](https://user-images.githubusercontent.com/43646136/234804789-fcc62cab-952f-4bc2-8ef9-adc4c5592c9f.png)

**Comment by AndraxDev** [comment]
Please note that restricting access to our servers helps use to provide you great experience and prevent abuse. We also perform apk integrity checks before accessing our resources. Our servers are not very powerfull and misuse may affect all users. Thanks for understanding. You can always download official apk and get rid of issues or contact me for API.
