### ISSUE TITLE
Feature Request: pressing back from chat to chatlist shouldn't scroll back to the top

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#63]
It makes it impossible to find a conversation

**Comment by AndraxDev** [comment]
Reduced amount of chat list updates. Chat list will no longer scroll up when you close a chat. Chat list scroll up only when model of some chats are changed or new chats are created/existing deleted. This is a behaviour of ListView. Planne dto migrate to RecyclerView in future. Fixed in SpeakGPT 3.12

**Comment by thiswillbeyourgithub** [comment]
Great work Andrax ! Thanks
