### ISSUE TITLE
About the control center(s)

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#94]
Hi,

I got mixed up between the control center windows today so I thought I'd share some constructive thoughts:
1. The control center for the chat should maybe rather be displayed as "Individual chat settings" and the global might be renamed "Global control center"
2. The red warning at the top of the global control center is nice, but it could be worth adding a red warning at the top of the individual chat setting saying "this is the setting for the chat 'my chat name'" or something. I don't see why you'd want to explicitely tell the user if s/he's in the global control settings but not in the chat settings
3. I think the presence of the "global" buttons in the chat settings are maybe confusing? Because if you are in the individual chat settings window you are not expecting to find those options : lock assistant window, amoled mode, auto save chats, delete data, the privacy section, the debug section, the other section.

Have a nice day!

**Comment by AndraxDev** [comment]
Rejected! The warning will be placed to simplify process of identifying global settings as many users confused when editing settings. Long text in activity title will create visual bugs on phones with small displays. The global options will not be hidden in chat settings because usually it is placed to the end of list. For example "Lock assistant window" can't be considered as local issues. This app is intended to use by adequate humand, not robots or idiots.

I think you're trying to criticize every line of code. But it's no sense to do this. I can understand issues like "A lot of untitled chats", but the most of your issues are not priority or have enough value. So please think carefully because too many issues may be considered a spam and will be removed and you will be blocked from publishing new issues. Thanks for understanding! I wish your next issues will be really important.

**Comment by AndraxDev** [comment]
To understand why I'm notifying users about they're modifying global settings see issues #10, #35, #54.
